name: UI Automation Tests

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu OS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your code from the repo
        
      - name: Set up Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo apt-get install -y curl
          sudo apt-get install -y unzip
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          sudo apt-add-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Install Microsoft Edge WebDriver
        run: |
          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}' | sed 's/\./\-/g')
          wget https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver-linux64.zip
          unzip edgedriver-linux64.zip
          sudo mv msedgedriver /usr/local/bin/
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Uses the Eclipse Temurin JDK

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests  # Installs dependencies but skips tests

      - name: Run Selenium Tests
        run: mvn test  # Executes all test cases

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: test-output/
          retention-days: 7

      

      
