name: UI Automation Tests

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu OS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your code from the repo

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # Uses the Eclipse Temurin JDK

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests  # Installs dependencies but skips tests

      # Set up Microsoft Edge
      - name: Set up Microsoft Edge
        uses: microsoft/setup-msedge@v1

      # Set up EdgeDriver
      - name: Set up EdgeDriver
        uses: microsoft/setup-msedge-driver@v1
        with:
          msedgedriver-version: 'latest'  # You can specify a version if needed

      # Install Edge dependencies (for headless mode)
      - name: Install Edge dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libxss1 libappindicator3-1 libindicator7

      - name: Run Selenium Tests
        run: mvn test  # Executes all test cases

      - name: Upload Extent Reports (Spark + PDF)
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports
          path: |
            test-output/SparkReport
            test-output/ExtentPdfReport.pdf
          if-no-files-found: warn  # Avoids failure if no reports are found
