name: UI Automation Tests

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu OS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your code from the repo

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Using Eclipse Temurin distribution for JDK 8

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests  # Installs dependencies but skips tests

      - name: Run Selenium Tests
        run: mvn test  # Executes all test cases

      # - name: Clean Old Reports
      #   run: rm -rf target/test-classes/test-output/* || true  # Cleanup old reports

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/test-classes/test-output/
          retention-days: 7
